# This is a basic workflow to help you get started with Actions
# https://github.com/marketplace/actions/test-container-image-scan
# https://learn.microsoft.com/en-us/azure/container-registry/github-action-scan

name: Scan Image

# Controls when the workflow will run
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  scan:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Scan image
        uses: Azure/container-scan@v0
        with:
          image-name: ghcr.io/oaviles/apid:master
          severity-threshold: CRITICAL
          run-quality-checks: true  
